/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#404944",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#707974",
        "outline-variant": "#bfc9c3",
        "surface-tint": "#2b6954",
        "primary": "#003527",
        "on-primary": "#ffffff",
        "primary-container": "#064e3b",
        "on-primary-container": "#80bea6",
        "inverse-primary": "#95d3ba",
        "secondary": "#a53c19",
        "on-secondary": "#ffffff",
        "secondary-container": "#fb7b54",
        "on-secondary-container": "#6b1a00",
        "tertiary": "#00237e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1238a8",
        "on-tertiary-container": "#9badff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b0f0d6",
        "primary-fixed-dim": "#95d3ba",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        "secondary-fixed": "#ffdbd1",
        "secondary-fixed-dim": "#ffb59f",
        "on-secondary-fixed": "#3a0a00",
        "on-secondary-fixed-variant": "#842503",
        "tertiary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed": "#001453",
        "on-tertiary-fixed-variant": "#173bab",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        
        // Cores específicas da marca e status do DESIGN.md
        "heritage-green-deep": "#064E3B",
        "heritage-green-leaf": "#166534",
        "material-terracotta": "#9A3412",
        "material-ochre": "#B45309",
        "institutional-blue": "#1E40AF",
        "surface-gray": "#F8FAFC",
        "border-subtle": "#E2E8F0",
        "status-critical": "#B91C1C",
        "status-warning": "#D97706",
        "status-stable": "#059669",
      },
      borderRadius: {
        "DEFAULT": "6px",
        "sm": "4px",
        "md": "6px",
        "lg": "8px",
        "xl": "12px",
        "2xl": "16px",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "stack-lg": "24px",
      },
      fontFamily: {
        "display-lg": ["\"Source Serif 4\""],
        "headline-lg": ["\"Source Serif 4\""],
        "headline-lg-mobile": ["\"Source Serif 4\""],
        "headline-md": ["\"Source Serif 4\""],
        "body-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "label-bold": ["Public Sans"],
        "label-caps": ["Public Sans"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
